# Generated by Django 5.0.2 on 2024-03-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nursiscool", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ouruser",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="users/profiles/"),
        ),
        migrations.AddField(
            model_name="ouruser",
            name="role",
            field=models.CharField(
                choices=[("1", "guest"), ("2", "admin"), ("3", "worker")],
                default="guest",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="users",
            field=models.ManyToManyField(
                related_name="vacancies", to="nursiscool.ouruser"
            ),
        ),
        migrations.AlterField(
            model_name="ouruser",
            name="password",
            field=models.CharField(max_length=25),
        ),
    ]
